### ISSUE TITLE
Формула

### ISSUE THREAD

**Issue by pupenasan** [pupenasan/avpbook#2]
$$ \gamma = \frac {\Delta}{N}.100% \tag {2.7} $$

**Comment by pavlo-shcherbukha** [comment]
#Варіант рішення проблеми

## Доопрацьована модель сайту

Наче б то вдалося доопацювати  підручник. 
Зробив окремий репозиторій (тестовий у себе).

URL головної сторінки підручника:   https://pshdevlab.github.io/formula/
URL repo:   https://github.com/pshdevlab/formula
Формули включені тільки на сторінці: https://pshdevlab.github.io/formula/2_2.html

![image](https://user-images.githubusercontent.com/52211585/178145861-ca817613-ffe5-4e7b-b374-48e7b8eee847.png)



Більш детально описано  тут : https://pavlo-shcherbukha.github.io/posts/2022-07-09/math/
Репозиторій: https://github.com/pavlo-shcherbukha/pavlo-shcherbukha.github.io

## Як вдалося відобразити формули


1. Ця установкамв _config.yml  практично ні на що не впливає, окрім стилю стандартного відображення 

```text
# theme: jekyll-theme-leap-day
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

```
2. Для відображення формул прийшлося перехопити  (перегрузити) основний frame (layout) сайту githubpages і руками включити на ньому завантаження mathjax

3. Щоб всі MD-файли відображались в одному  frame (layout) до кожного файлу додано заголовок:

```text

---
layout: default
use_math: false
---
```
А на сторінці з формулами включено   завантаження mathjax

```text
---
layout: default
use_math: true
---
```
Сам  шаблон знаходиться в  [default.html](https://github.com/pshdevlab/formula/blob/main/_layouts/default.html)
Він обрізаний торохи. може не акуратно, але там простий html, можна розширити.

В фрагменті: 

```text

    {% if page.use_math %}
      {% include mathjax_support.html %}
    {% endif %}

```
завантажується  mathjax_ з файлу  [mathjax_support.html](https://github.com/pshdevlab/formula/blob/main/_includes/mathjax_support.html), за умови, що на сторінці включено:  use_math: true, [2_2.md](https://github.com/pshdevlab/formula/blob/main/2_2.md).


4. Каталог **_sass**  потрібен для функціонування jekyll  (без нього не генеруеться)

5. Каталог **assets** використовується для збереження стилів, шрифтів, картинок. Ну це кастомне і його модна поділити або об'єднати


Ну, наче все. А ще _config.yml    додано додаткові реквізити та приклади, як їх можна використати 👍 

```text
title: Тестова розробка
description: Тестова сторінка для фомул
author: Тестовий сайт
logo: /assets/img/robot-1.jpg

``` 

а ось як вони підставляються в layout:


```text
   <div class="wrapper">
      <header>
        <h1><a href="{{ "/" | absolute_url }}">{{ site.title | default: site.github.repository_name }}</a></h1>

        {% if site.logo %}
          <img src="{{site.logo | relative_url}}" alt="Logo" />
        {% endif %}

        <p>{{ site.description | default: site.github.project_tagline }}</p>



      </header>
      <section>

```




І на останок, сайте стартує зі сторінки index.md.  Я просто перейменував  readme.md  в index.md

**Comment by pavlo-shcherbukha** [comment]
Блоги

Щоб ширше виокристовувати  можливості Github pages  є ще на  https://github.com/pavlo-shcherbukha/pavlo-shcherbukha.github.io таке поняття як блоги.

Там всі файли знаходяться в каталозі: https://github.com/pavlo-shcherbukha/pavlo-shcherbukha.github.io/tree/main/_posts

 а шаблон блога https://github.com/pavlo-shcherbukha/pavlo-shcherbukha.github.io/blob/main/_layouts/post.html розширює шаблон ..._layouts/default.html

Ну там є особливості, зо відоюражаються в заголовку:

```text
---
layout: post
title: "Почтаток роботи з MySQL"  # заголовок сторінки (в термінах браузера)
date: 2022-04-28 10:00:01  #  Дата, раніше якої воно появиться в переліку
categories: [mysql]  # теги (але пошуку по ним поки немає)
permalink: posts/2022-04-28/mysql-labs/ # постійний URL
published: true   # публікувати-не публікувати 
use_math: true  #  ну і завантажувати відображення  формул чи ні 
---

```

**Comment by pupenasan** [comment]
> 
>     3. Щоб всі MD-файли відображались в одному  frame (layout) до кожного файлу додано заголовок:

Не зрозумів цього. Навіщо умову відображення формул потрібно? Хай вважає що вона є на всіх сторінках, тоді і умовне використання не потрібне і лишній текст не треба писати в MD.

**Comment by pavlo-shcherbukha** [comment]
> 3. Щоб всі MD-файли відображались в одному  frame (layout) до кожного файлу додано заголовок:

Тут малося на увазі не включення/виключення математичних формул, а що сторінка відображається як фрагмент сторінки  _ layouts/default.html, в розділі:

```html
      <section>

      {{ content }}

      </section>

```
Тому в кожному md-файлі вказано

```text
---
layout: default
--
```

З приводу  **use_math: false** -  можна не вказувати. ТАм логіка така, що, коли не true -  то false

**Comment by pupenasan** [comment]
Зробив дві зміни:
- завантажив оригінальний default.html в `_layout` і вписав туди `{% include head-custom.html %}`
- створив `_includes` і включив туди файл  mathjax_support.html, який взяв у Вас. І все запрацювало!

https://pupenasan.github.io/avpbook/2_2.html

Дякую!
